apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: wnkj769rm-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.94063222-f67e-48ae-a597-8d8c44f683bb.prod.konfluxeaas.com/rhtap/rhtap-qe-dotnet-basic:2d443dd0422ba24742fe2f97b47fb26d694a0b7f@sha256:181861b48e1da7453171c7514e81b7e0f80baf32ac0a6bda061901ad7a4a6520
          name: container-image
